### ISSUE TITLE
nodered bulb node

### ISSUE THREAD

**Issue by sunsharebox** [kprinssu/node-smart-bulb#2]
I'm trying to control a bluetooth beewi bulb lamp (2) with my raspberry under nodered. Il is very similar to your trial. Would you help me install it ? I'm not used to js.
If not, could you help us to solve the transfer of this python script (1) to a nodered add-on ? It works with my lamp.
Thank you. Julien
(1) https://www.raspberrypi.org/forums/viewtopic.php?t=117729#p1446633
(2) https://github.com/sunsharebox/sunlight

**Comment by kprinssu** [comment]
It's been about 5 years since I last touched the project. The project that I suggest you look at https://github.com/abandonware/noble for the JS side of things, it handles the BLE communications (upstream has not been updated in 2 years). 

Do you need anything particular for intercepting Bluetooth communications? If your bulb has Android support, I suggest enabling Bluetooth debugging and dumping the logs of an Android device. Otherwise, you're looking at investing into a $100 Bluetooth adapter to sniff the packets.
